version: '3.7'

services:

  node1:
    image: ${P2P_NODE_IMAGE}
    container_name: node1
    # sysctls:
    #   net.core.rmem_max: 26214400
    #   net.core.wmem_max: 26214400
    #   net.core.rmem_default: 26214400
    #   net.core.wmem_default: 26214400
    command: sh -c "sysctl -p /etc/sysctl.conf && routing -boot-addr=/ip4/192.168.0.2/tcp/2002/p2p/12D3KooWRTr7YuSZPzDCkG4oywVD2M5YxmgHud6X2MUiFYkDnsbQ"
    networks:
      net:
        ipv4_address: 192.168.0.4

  node2:
    image: ${P2P_NODE_IMAGE}
    container_name: node2
    # sysctls:
    #   net.core.rmem_max: 26214400
    #   net.core.wmem_max: 26214400
    #   net.core.rmem_default: 26214400
    #   net.core.wmem_default: 26214400
    command: sh -c "sysctl -p /etc/sysctl.conf && routing -boot-addr=/ip4/192.168.0.2/tcp/2002/p2p/12D3KooWRTr7YuSZPzDCkG4oywVD2M5YxmgHud6X2MUiFYkDnsbQ"
    networks:
      net:
        ipv4_address: 192.168.0.5  

networks:
  net:
    name: ${P2P_NET_EX3}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.254

