version: '3.7'

services:

  node1:
    image: ${P2P_NODE_IMAGE}
    container_name: node1
    command: -port=2002
    ports:
      - 2001:2002
    volumes:
      - vol:/opt
    networks:
      net:
        ipv4_address: 192.168.0.1

  node2:
    image: ${P2P_NODE_IMAGE}
    container_name: node2
    command: -port=2002 -laddr=/ip4/192.168.0.1/tcp/2002/p2p/12D3KooWDawPwZAEHk3An2bPJFkvzzCNVNRDvVH6yU6g58KRcd4X
    ports:
      - 2002:2002
    volumes:
      - vol:/opt
    networks:
      net:
        ipv4_address: 192.168.0.2
  
networks:
  net:
    name: ${P2P_NETWORK_EX1}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.254

volumes:
  vol:
    name: ${P2P_VOLUME_EX1}