version: '3.7'

services:

  playground:
    image: ${PLAYGROUND_IMAGE}
    container_name: ${PLAYGROUND_CONTAINER}
    working_dir: /opt
    volumes:
      - vol:/opt
    networks:
      - local

networks:
  local:
    name: $NETWORK

volumes:
  vol:
    name: $PLAYGROUND_VOLUME