version: '3.7'

services:

  playground:
    image: ${PLAYGROUND_IMAGE}
    container_name: ${PLAYGROUND_CONTAINER}
    working_dir: /opt
    networks:
      local:
        ipv4_address: 192.168.0.2

networks:
  local:
    name: ${PLAYGROUND_NETWORK}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.254
